// <auto-generated />
namespace Forum.Persistence.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.1-30610")]
    public sealed partial class delete_fk : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(delete_fk));
        
        string IMigrationMetadata.Id
        {
            get { return "201412012051302_delete_fk"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
